# Generated by Django 4.2.4 on 2023-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('BE', 'Beverage'), ('MC', 'Main Course'), ('W', 'W'), ('SR', 'Starter'), ('SP', 'Soup'), ('DT', 'Desert'), ('AL', 'Alcohol')], default=12, max_length=2),
            preserve_default=False,
        ),
    ]
