# Generated by Django 4.2.4 on 2023-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('AL', 'Alcohol'), ('MC', 'Main Course'), ('DT', 'Desert'), ('W', 'W'), ('SP', 'Soup'), ('BE', 'Beverage'), ('SR', 'Starter')], max_length=2),
        ),
    ]
