# Generated by Django 4.2.4 on 2023-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_menuitem_description_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('AL', 'Alcohol'), ('SR', 'Starter'), ('DT', 'Desert'), ('W', 'W'), ('BE', 'Beverage'), ('MC', 'Main Course'), ('SP', 'Soup')], max_length=2),
        ),
    ]
