# Generated by Django 4.2.4 on 2023-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('SR', 'Starter'), ('MC', 'Main Course'), ('AL', 'Alcohol'), ('W', 'W'), ('SP', 'Soup'), ('BE', 'Beverage'), ('DT', 'Desert')], max_length=2),
        ),
    ]
