# Generated by Django 4.2.4 on 2024-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('AL', 'Alcohol'), ('MC', 'Main Course'), ('SP', 'Soup'), ('DT', 'Desert'), ('SR', 'Starter'), ('BE', 'Beverage'), ('W', 'W')], max_length=2),
        ),
    ]
