# Generated by Django 4.2.4 on 2024-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('MC', 'Main Course'), ('W', 'W'), ('SR', 'Starter'), ('SP', 'Soup'), ('DT', 'Desert'), ('BE', 'Beverage'), ('AL', 'Alcohol')], max_length=2),
        ),
    ]
