# Generated by Django 4.2.4 on 2024-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('MC', 'Main Course'), ('DT', 'Desert'), ('SR', 'Starter'), ('AL', 'Alcohol'), ('SP', 'Soup'), ('W', 'W'), ('BE', 'Beverage')], max_length=2),
        ),
    ]
