# Generated by Django 4.2.4 on 2023-08-31 14:39

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/projects/resturant_control/mediafiles')),
        ),
    ]
